# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
