# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_date',
        ),
    ]
