# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='New', max_length=50),
            preserve_default=False,
        ),
    ]
