# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200217_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=10),
        ),
    ]
