# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-18 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='reporter',
            new_name='submitted_by',
        ),
    ]
