# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_ticket_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitted_by',
            field=models.CharField(default='bruce', max_length=50),
            preserve_default=False,
        ),
    ]
