# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_ticket_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(default='Unassigned', max_length=200),
        ),
    ]
