# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20200219_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='upvotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
