# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20200219_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
