# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-19 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_body',
        ),
    ]
