# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20200219_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
