# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-21 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_changehistory_historicalticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changehistory',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChangeHistory',
        ),
    ]
